apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: openhands
    title: OpenHands
    description: Este repositório busca documentar a arquitetura e os usos do OpenHands para a criação de um gerador de aplicações. Além disso, estão armazenados os microagentes e exemplos úteis para o aprimoramento do OpenHands, visando o objetivo citado.
    annotations:
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: Agents4Good/OpenHands

spec:
    type: service
    lifecycle: development
    owner: Geração
